import 'package:flutter/material.dart';

const active = EdgeInsets.only(top: 20);
const notActive = EdgeInsets.only(top: 100);
var name;
var token;
List tokendec = [];
List glucose_test = [];
List treatment = [];
List glucose_con = [];
List Userprofile = [];
List activity = [];
List activity_con = [];
var min = 0;
double avg = 0;
int avgS = 0;
var A1C = 0.0;
var max = 0;
var weight = 0;
var height = 0;
var bmi = 0.0;
var Protein = 0;
var Carbs = 0;
var Calories = 0;
var Fat = 0;
var Steps = 0;
var Calories_Burnt = 0;
var patientid;
